### PR TITLE
Lots of Code Tweaks and String Updates

### PR DESCRIPTION
**Pull request by lucidlemon**
I hope you are fine with merging back your awesome work into the main repo @awebeer256 ? I would appreciate it.

### CODE REVIEW

**Comment by awebeer256** [comment]
> I hope you are fine with merging back your awesome work into the main repo @awebeer256 ? I would appreciate it.

That was the plan, yes, but it hasn't really been tested yet, so you might want to hold off. Or call it a beta, maybe. ¯\\_(ツ)_/¯ You can merge if you think it's ready.

**Comment by awebeer256** [comment]
Okay, never mind: there are **definitely** some bugs. Hold on.

**Comment by awebeer256** [comment]
Okay, test the current version yourself, and if everything looks like it's working, *then* you can merge it. ;)

**Comment by lucidlemon** [comment]
seems to work and build just fine 👌

**Pull request merged**
